### ISSUE TITLE
New users added are not saved

### ISSUE THREAD

**Issue by SteveMarvin** [AVAnnotate/admin-client#110]
Users can be added via the dialog, but once save is clicked, they go away and the user is returned to the home page. New users are subsequently not on the user list or the project card.

**Comment by SteveMarvin** [comment]
I'm not seeing this. When I invited Lorin, he showed up without the (invite), and appeared immediately on the project card. When I reentered the project and checked the Settings/users, his name was no longer there.

When I invited Camden, he remains on the Settings user list, but does not have (invited). He also appears on the project card.

**Comment by lwjameson** [comment]
@SteveMarvin Unfortunately both users you added are on the Performant Team in the AVAnnotate org.  Run your test in your own org.

**Comment by SteveMarvin** [comment]
OK, when in my own org, it works fine. ;-) Accepted
