### ISSUE TITLE
Disable saving on the duration modal until all durations are entered

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#141]
It's possible to save this modal even if fields aren't completed, which leads to the same issue of empty Event durations and build fails. Let's only allow users to save once all fields have been completed.

**Comment by SteveMarvin** [comment]
was able to enter a start time without entering an end time, was saved
![image](https://github.com/user-attachments/assets/3072ab9e-1b42-44ac-8df6-3df3dbdc6c70)
![image](https://github.com/user-attachments/assets/01d8e6ff-3d0d-4f46-bda5-c4a608b7e198)

**Comment by camdendotlol** [comment]
@SteveMarvin This issue was about the duration modal on the event import form - I don't think anyone has proposed a similar feature for the annotation modal yet. It might be a good idea if you want to file a new issue for it.
