### ISSUE TITLE
Feature request: Human-readable URLs

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#146]
As a scholar or student, I want easy and relatively permanent ways to share and cite project pages. I might send an individual page to a colleague or may publish my project through a scholarly journal.

Something like https://avannotate.github.io/develop-bishop/pages/0ceb0aaf-8d35-4956-b2b6-adad45568ee0/ is not nearly as understandable as https://avannotate.github.io/develop-bishop/pages/introduction/

Could Page titles be used to generate slugs? Or could the user be prompted to enter a page slug?

**Comment by lwjameson** [comment]
@absempere We just could not guarantee that the title was unique, or that it was not overly long (you know how often we have been surprised by the verbosity of users). While this may be possible, I would prefer to hold off on this for now.
