### ISSUE TITLE
Editing the event description makes all of the text disappear

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#191]
Screen recording of what's happening for Tanya. I was unable to replicate this.

https://github.com/user-attachments/assets/b69cd069-bc50-40f2-94de-3876d21bd630

**Comment by camdendotlol** [comment]
Looks like this event was created via import. Can I see the CSV it came from?

**Comment by absempere** [comment]
@camdendotlol These are the same Zora Neale Hurton spreadsheets we've been using for all of our testing. 
[Annotationsv3.zip](https://github.com/user-attachments/files/17722187/Annotationsv3.zip)

**Comment by camdendotlol** [comment]
Hm, that zip file seems to be something else and I can't seem to find the T86 CSVs in Slack.

I'm pretty sure I have a fix and I can create a test CSV to import but I won't feel super confident until I can verify the fix with the original CSV used above.

**Comment by camdendotlol** [comment]
Found it, I think. It's saved as "AVAnnotate_Event_Template.csv" in Slack but it contains several of the ZNH events.
