### ISSUE TITLE
Text overflow on pasted text

### ISSUE THREAD

**Issue by absempere** [AVAnnotate/admin-client#94]
From Ben: When I try creating an event via the UI and paste in the first three paragraphs from [this wikipedia page](https://en.wikipedia.org/wiki/The_Louvin_Brothers) into the event description, the text overflows the editor.  See screenshot:

![Screenshot from 2024-09-16 12-51-18](https://github.com/user-attachments/assets/36c0fe33-dba6-4888-80eb-c9272465bc10)

Note that the text saves successfully, so this just seems like a CSS/JS issue with the editor.

![Screenshot from 2024-09-16 12-55-12](https://github.com/user-attachments/assets/f5133f87-a363-407c-aa30-bc22a3a83f44)

**Comment by SteveMarvin** [comment]
I'm still seeing this.
